name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches: [main, master]
    paths:
      - "docs/**"
  pull_request:
    branches: [main, master]
    paths:
      - "docs/**"

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r docs/requirements.txt

      - name: Build docs
        run: cd docs && make html

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: html-docs
          path: docs/_build/html/

      - name: Deploy to gh-pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/_build/html
          commit-message: Update docs site
